global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'emailbot'
    static_configs:
      - targets: ['emailbot-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'emailbot-health'
    static_configs:
      - targets: ['emailbot-app:8000']
    metrics_path: '/health'
    scrape_interval: 60s 