global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: 'emailbot-app'
    static_configs:
      - targets: ['emailbot-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'emailbot-postgres'
    static_configs:
      - targets: ['emailbot-postgres:5432']
    scrape_interval: 30s

  - job_name: 'emailbot-redis'
    static_configs:
      - targets: ['emailbot-redis:6379']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['emailbot-node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s 